# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='aws.kinesis.protobuf',
  serialized_pb=_b('\n\x0c\x63onfig.proto\x12\x14\x61ws.kinesis.protobuf\"F\n\x13\x41\x64\x64itionalDimension\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\x12\x13\n\x0bgranularity\x18\x03 \x02(\t\"\x8b\x07\n\rConfiguration\x12J\n\x16\x61\x64\x64itional_metric_dims\x18\x80\x01 \x03(\x0b\x32).aws.kinesis.protobuf.AdditionalDimension\x12!\n\x13\x61ggregation_enabled\x18\x01 \x01(\x08:\x04true\x12)\n\x15\x61ggregation_max_count\x18\x02 \x01(\x04:\n4294967295\x12#\n\x14\x61ggregation_max_size\x18\x03 \x01(\x04:\x05\x35\x31\x32\x30\x30\x12\x1d\n\x13\x63loudwatch_endpoint\x18\x04 \x01(\t:\x00\x12\x1c\n\x0f\x63loudwatch_port\x18\x05 \x01(\x04:\x03\x34\x34\x33\x12!\n\x14\x63ollection_max_count\x18\x06 \x01(\x04:\x03\x35\x30\x30\x12$\n\x13\x63ollection_max_size\x18\x07 \x01(\x04:\x07\x35\x32\x34\x32\x38\x38\x30\x12\x1d\n\x0f\x63onnect_timeout\x18\x08 \x01(\x04:\x04\x36\x30\x30\x30\x12 \n\x11\x65nable_core_dumps\x18\t \x01(\x08:\x05\x66\x61lse\x12 \n\x11\x66\x61il_if_throttled\x18\n \x01(\x08:\x05\x66\x61lse\x12\x1a\n\x10kinesis_endpoint\x18\x0b \x01(\t:\x00\x12\x19\n\x0ckinesis_port\x18\x0c \x01(\x04:\x03\x34\x34\x33\x12\x17\n\tlog_level\x18\r \x01(\t:\x04info\x12\x1b\n\x0fmax_connections\x18\x0e \x01(\x04:\x02\x32\x34\x12\"\n\x13metrics_granularity\x18\x0f \x01(\t:\x05shard\x12\x1f\n\rmetrics_level\x18\x10 \x01(\t:\x08\x64\x65tailed\x12\x31\n\x11metrics_namespace\x18\x11 \x01(\t:\x16KinesisProducerLibrary\x12#\n\x14metrics_upload_delay\x18\x12 \x01(\x04:\x05\x36\x30\x30\x30\x30\x12\x1a\n\x0fmin_connections\x18\x13 \x01(\x04:\x01\x31\x12\x17\n\nrate_limit\x18\x14 \x01(\x04:\x03\x31\x35\x30\x12%\n\x18record_max_buffered_time\x18\x15 \x01(\x04:\x03\x31\x30\x30\x12\x19\n\nrecord_ttl\x18\x16 \x01(\x04:\x05\x33\x30\x30\x30\x30\x12\x10\n\x06region\x18\x17 \x01(\t:\x00\x12\x1d\n\x0frequest_timeout\x18\x18 \x01(\x04:\x04\x36\x30\x30\x30\x12 \n\x12verify_certificate\x18\x19 \x01(\x08:\x04true')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ADDITIONALDIMENSION = _descriptor.Descriptor(
  name='AdditionalDimension',
  full_name='aws.kinesis.protobuf.AdditionalDimension',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='aws.kinesis.protobuf.AdditionalDimension.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='aws.kinesis.protobuf.AdditionalDimension.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='granularity', full_name='aws.kinesis.protobuf.AdditionalDimension.granularity', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=108,
)


_CONFIGURATION = _descriptor.Descriptor(
  name='Configuration',
  full_name='aws.kinesis.protobuf.Configuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='additional_metric_dims', full_name='aws.kinesis.protobuf.Configuration.additional_metric_dims', index=0,
      number=128, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aggregation_enabled', full_name='aws.kinesis.protobuf.Configuration.aggregation_enabled', index=1,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aggregation_max_count', full_name='aws.kinesis.protobuf.Configuration.aggregation_max_count', index=2,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=4294967295,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aggregation_max_size', full_name='aws.kinesis.protobuf.Configuration.aggregation_max_size', index=3,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=51200,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cloudwatch_endpoint', full_name='aws.kinesis.protobuf.Configuration.cloudwatch_endpoint', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cloudwatch_port', full_name='aws.kinesis.protobuf.Configuration.cloudwatch_port', index=5,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=443,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collection_max_count', full_name='aws.kinesis.protobuf.Configuration.collection_max_count', index=6,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=500,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collection_max_size', full_name='aws.kinesis.protobuf.Configuration.collection_max_size', index=7,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=5242880,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connect_timeout', full_name='aws.kinesis.protobuf.Configuration.connect_timeout', index=8,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=6000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_core_dumps', full_name='aws.kinesis.protobuf.Configuration.enable_core_dumps', index=9,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fail_if_throttled', full_name='aws.kinesis.protobuf.Configuration.fail_if_throttled', index=10,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kinesis_endpoint', full_name='aws.kinesis.protobuf.Configuration.kinesis_endpoint', index=11,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kinesis_port', full_name='aws.kinesis.protobuf.Configuration.kinesis_port', index=12,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=443,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_level', full_name='aws.kinesis.protobuf.Configuration.log_level', index=13,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("info").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_connections', full_name='aws.kinesis.protobuf.Configuration.max_connections', index=14,
      number=14, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=24,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metrics_granularity', full_name='aws.kinesis.protobuf.Configuration.metrics_granularity', index=15,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("shard").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metrics_level', full_name='aws.kinesis.protobuf.Configuration.metrics_level', index=16,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("detailed").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metrics_namespace', full_name='aws.kinesis.protobuf.Configuration.metrics_namespace', index=17,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("KinesisProducerLibrary").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metrics_upload_delay', full_name='aws.kinesis.protobuf.Configuration.metrics_upload_delay', index=18,
      number=18, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=60000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_connections', full_name='aws.kinesis.protobuf.Configuration.min_connections', index=19,
      number=19, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rate_limit', full_name='aws.kinesis.protobuf.Configuration.rate_limit', index=20,
      number=20, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=150,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='record_max_buffered_time', full_name='aws.kinesis.protobuf.Configuration.record_max_buffered_time', index=21,
      number=21, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='record_ttl', full_name='aws.kinesis.protobuf.Configuration.record_ttl', index=22,
      number=22, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=30000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='region', full_name='aws.kinesis.protobuf.Configuration.region', index=23,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_timeout', full_name='aws.kinesis.protobuf.Configuration.request_timeout', index=24,
      number=24, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=6000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='verify_certificate', full_name='aws.kinesis.protobuf.Configuration.verify_certificate', index=25,
      number=25, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=1018,
)

_CONFIGURATION.fields_by_name['additional_metric_dims'].message_type = _ADDITIONALDIMENSION
DESCRIPTOR.message_types_by_name['AdditionalDimension'] = _ADDITIONALDIMENSION
DESCRIPTOR.message_types_by_name['Configuration'] = _CONFIGURATION

AdditionalDimension = _reflection.GeneratedProtocolMessageType('AdditionalDimension', (_message.Message,), dict(
  DESCRIPTOR = _ADDITIONALDIMENSION,
  __module__ = 'config_pb2'
  # @@protoc_insertion_point(class_scope:aws.kinesis.protobuf.AdditionalDimension)
  ))
_sym_db.RegisterMessage(AdditionalDimension)

Configuration = _reflection.GeneratedProtocolMessageType('Configuration', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATION,
  __module__ = 'config_pb2'
  # @@protoc_insertion_point(class_scope:aws.kinesis.protobuf.Configuration)
  ))
_sym_db.RegisterMessage(Configuration)


# @@protoc_insertion_point(module_scope)
